name: Manual workflow Test

on:
  workflow_dispatch:
    inputs:
      component_name:
        description: 'select the component that should be approved'
        required: true
        type: choice
        options:
          - "Button Primary"
          - Link

jobs:
  # This workflow contains a single job called "greet"
  approve:
    runs-on: ubuntu-latest
    steps:
    - name: Approve Component
      run: echo "Approve new golden samples of ${{ inputs.componentName }}"
